# Site settings
name: ttkmw's DevLog
email: wom2277@naver.com
author: Geunwon Lim
url: https://ttkmw.github.io
resume_site:
github: https://github.com/ttkmw
baseurl: ""
description: my footprint on development
meta_description:
motto: Enjoy My Posts
banner: Try To Keep My Word
lsi: false
safe: true
source: https://ttkmw.github.io
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge




#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: ttkmw

# Build settings
markdown: kramdown

baidu_analysis: 94be4b0f9fc5d94cc0d0415ea6761ae9

