# Site settings
name: inDlife's DevLog
email: wom2277@naver.com
author: Geunwon Lim
url: https://indlife.github.io
resume_site:
github: https://github.com/inDlife
baseurl: ""
description: my footprint on development
meta_description:
motto: Independent Life
banner: Independent Lifes



#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: inDlife

# Build settings
markdown: kramdown

baidu_analysis: 94be4b0f9fc5d94cc0d0415ea6761ae9

