# Site settings
name: p-vibe's DevLog
email: wom2277@naver.com
author: Geunwon Lim
url: https://p-vibe.github.io
resume_site:
github: https://github.com/p-vibe
baseurl: ""
description: my footprint on development
meta_description:
motto: Enjoy My Posts
banner: Positive Vibe
lsi: false
safe: true
source: https://p-vibe.github.io
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge




#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: p-vibe

# Build settings
markdown: kramdown

baidu_analysis: 94be4b0f9fc5d94cc0d0415ea6761ae9

